Track = Struct.new(
  :album,
  :album_artist,
  :album_loved,
  :album_rating,
  :album_rating_computed,
  :apple_music,
  :artist,
  :artwork_count,
  :bit_rate,
  :bpm,
  :clean,
  :comments,
  :compilation,
  :composer,
  :date_added,
  :date_modified,
  :disc_count,
  :disc_number,
  :explicit,
  :favorited,
  :file_folder_count,
  :genre,
  :grouping,
  :has_video,
  :hd,
  :kind,
  :library_folder_count,
  :location,
  :loved,
  :matched,
  :movement_count,
  :movement_name,
  :movement_number,
  :music_video,
  :name,
  :normalization,
  :part_of_gapless_album,
  :persistent_id,
  :play_count,
  :play_date,
  :play_date_utc,
  :playlist_only,
  :protected,
  :rating,
  :release_date,
  :sample_rate,
  :size,
  :skip_count,
  :skip_date,
  :sort_album,
  :sort_album_artist,
  :sort_artist,
  :sort_composer,
  :sort_name,
  :total_time,
  :track_count,
  :track_id,
  :track_number,
  :track_type,
  :work,
  :year,
  keyword_init: true
) do
  def get_album
    Album.new(
      artist: album_artist,
      genre: genre,
      loved: album_loved,
      rating: album_rating,
      name: album,
      year: year
    )
  end
end
