#!/usr/bin/env ruby
# frozen_string_literal: true

require './utilities/apple_music_library_parser'

# Percent widths are unreliable inside auto-sized table cells, so bars get a
# fixed pixel budget instead.
def bar(value, max, budget_px: 120)
  width = [(value * budget_px.to_f / max).round, 2].max
  "<span style=\"display:inline-block;background:var(--c-link);height:0.75em;width:#{width}px\"></span>"
end

LIBRARY_FILE = 'Library.xml'
parser = AppleMusicLibraryParser.new(LIBRARY_FILE)

PAGE_PATH = 'blog/listening/index.md'
# The serial number is assigned by utilities/serialize after the fact, so a
# regeneration must carry it forward or it would be silently dropped.
serial_number = File.read(PAGE_PATH)[/^serial_number: .+$/] if File.exist?(PAGE_PATH)

file = File.open(PAGE_PATH, 'w')
file.puts '---'
file.puts 'layout: Page'
file.puts 'title: Music Listening'
file.puts 'toc: true'
file.puts 'emoji: 🎶'
file.puts 'searchable: true'
file.puts 'categories:'
file.puts '- blog'
file.puts 'tags:'
file.puts '- music'
file.puts '- index'
file.puts 'redirect_from:'
file.puts '- /music'
file.puts serial_number if serial_number
file.puts '---'
file.puts <<~LIQUID
  Albums that moved me enough to write about them.

  {% assign postsByMonth = site.categories['listening'] | group_by_exp:"post", "post.date | date: '%Y'" %}
  {% for day in postsByMonth %}
    <table>
        <thead>
          <tr>
              <td colspan="3">
                  <span id="{{ day.name }}">{{ day.name }}</span>
              </td>
          </tr>
        </thead>
    {% for post in day.items %}
    {%- include PostTableRow.html post=post -%}
    {% endfor %}
    </table>
  {% endfor %}
LIQUID
file.puts
file.puts '## Listening Stats'
file.puts 'I generate this page from my Apple Music library using [a script I wrote](/blog/pulling-fun-insights-out-of-my-apple-music-library). Feel free to use it, too!'
file.puts
file.puts "Last updated: #{File.mtime(LIBRARY_FILE).strftime('%Y-%m-%d')}"
file.puts
file.puts '## Recently Played Albums'
file.puts 'This is a list of the albums I\'ve played recently.'
file.puts
file.puts '| Art | Artist | Album |'
file.puts '| --- | ------ | ----- |'
parser.recently_played_albums.each do |album|
  album.download_album_art
  file.puts "| #{album.album_art_md} | #{album.artist} | #{album.name} |"
end
file.puts
file.puts '## Recently Loved Albums'
file.puts 'This is a list of the albums I\'ve loved recently.'
file.puts
file.puts '| Art | Artist | Album |'
file.puts '| ------ | ----- | --------- |'
parser.recently_loved_albums.each do |album|
  album.download_album_art
  file.puts "| #{album.album_art_md} | #{album.artist} | #{album.name} |"
end
file.puts
file.puts '## Forgotten Favorites'
file.puts 'Loved tracks I haven\'t played in the longest time.'
file.puts
file.puts '| Artist | Track | Last Played |'
file.puts '| ------ | ----- | ----------- |'
parser.forgotten_loved_tracks(limit: 10).each do |track|
  last_played = track.play_date_utc ? track.play_date_utc.strftime('%Y-%m-%d') : 'never'
  file.puts "| #{track.artist} | #{track.name} | #{last_played} |"
end
file.puts
file.puts '## Top Played Tracks'
file.puts 'This is a list of the top played tracks in my library.'
file.puts
file.puts '| Artist | Album | Track | Play Count | Listening Time |'
file.puts '| ------ | ----- | ----- | ---------- | -------------- |'
parser.top_played_tracks.each do |track|
  track.get_album.download_album_art
  time = (track.play_count * track.total_time) / 1000
  time_format = "#{time / 3600}h #{(time % 3600) / 60}m #{time % 60}s"
  album_md = track.get_album.album_art_md
  album_md = track.album if album_md.nil? || album_md.empty?
  file.puts "| #{track.artist} | #{album_md} | #{track.name} | #{track.play_count} | #{time_format} |"
end
file.puts
file.puts '## Top Played Albums'
file.puts 'This is a list of the top played albums in my library (by ratio of song plays to songs in the album).'
file.puts
file.puts '| Art | Artist | Album | Song Play Ratio | Play Count'
file.puts '| --- | ------ | ----- | --------------- | --------- |'
parser.top_played_albums.each do |album|
  album.download_album_art
  file.puts "| #{album.album_art_md} | #{album.artist} | #{album.name} | #{album.song_play_ratio.round} | #{album.song_play_count} |"
end
file.puts
file.puts '## Top Played Artists'
file.puts 'This is a list of the top played artists in my library (by song plays).'
file.puts
file.puts '| Artist | Song Play Count | Song Play Ratio |'
file.puts '| ------ | -------------- | --------------- |'
parser.top_played_artists.each do |artist|
  file.puts "| #{artist.name} | #{artist.song_play_count} | #{artist.song_play_ratio.round} |"
end
file.puts
file.puts '## Top Genres'
file.puts 'This is a list of the top genres my library (by track count).'
file.puts
file.puts '| Genre | Track Count | Song Play Count | Total Time |'
file.puts '| ------ | ---------- | -------------- | --------------- |'
parser.top_genres.each do |genre|
  time = genre.total_time / 1000
  time_format = "#{time / 3600}h #{(time % 3600) / 60}m #{time % 60}s"
  file.puts "| #{genre.name} | #{genre.track_count} | #{genre.play_count} | #{time_format} |"
end
file.puts
file.puts '## Play Concentration'
file.puts 'How unevenly my plays are distributed across the library.'
file.puts
concentration = parser.play_concentration
never = parser.never_played
file.puts "- #{concentration[:total_plays]} total plays across the library"
file.puts "- The top 1% of tracks account for #{concentration[:top_1_pct].round}% of all plays"
file.puts "- The top 5% of tracks account for #{concentration[:top_5_pct].round}% of all plays"
file.puts "- The top 10% of tracks account for #{concentration[:top_10_pct].round}% of all plays"
file.puts "- #{never[:count]} tracks (#{never[:pct].round}%) have never been played"
file.puts
file.puts '## Library Growth'
file.puts 'Tracks added to my library by year.'
file.puts
file.puts '| Year | Tracks Added | |'
file.puts '| ---- | ------------ | --- |'
added_by_year = parser.tracks_added_by_year
max_added = added_by_year.values.max
added_by_year.each do |year, count|
  file.puts "| #{year} | #{count} | #{bar(count, max_added)} |"
end
file.puts
file.puts '## Taste Drift'
file.puts 'The top genres of the tracks I added each year.'
file.puts
file.puts '| Year | Top Genres Added |'
file.puts '| ---- | ---------------- |'
parser.top_genres_by_added_year.each do |year, genres|
  genre_list = genres.map { |genre, count| "#{genre} (#{count})" }.join(' · ')
  file.puts "| #{year} | #{genre_list} |"
end
file.puts
file.puts '## Library by Release Decade'
file.puts 'When the music in my library was originally released.'
file.puts
file.puts '| Decade | Tracks | Plays | |'
file.puts '| ------ | ------ | ----- | --- |'
by_decade = parser.tracks_by_release_decade
max_decade = by_decade.map { |_, stats| stats[:count] }.max
by_decade.each do |decade, stats|
  file.puts "| #{decade}s | #{stats[:count]} | #{stats[:plays]} | #{bar(stats[:count], max_decade)} |"
end
file.puts
file.puts '## One-Hit Wonders'
file.puts 'Artists where a single track soaks up most of my plays (min. 5 tracks and 100 plays).'
file.puts
file.puts '| Artist | The Hit | Hit Plays | All Plays | Share |'
file.puts '| ------ | ------- | --------- | --------- | ----- |'
parser.one_hit_wonders.each do |hit|
  file.puts "| #{hit[:artist]} | #{hit[:track]} | #{hit[:track_plays]} | #{hit[:total_plays]} | #{hit[:share].round}% |"
end
file.puts
file.puts '## Album Loyalty'
file.puts 'Whether I play an album front-to-back or cherry-pick tracks, measured by how evenly plays spread across its tracks (min. 4 tracks and 5 plays per track on average).'
loyalty = parser.album_loyalty
file.puts
file.puts '### Front-to-Back'
file.puts
file.puts '| Artist | Album | Album Plays |'
file.puts '| ------ | ----- | ----------- |'
loyalty[:front_to_back].each do |album, _cv|
  file.puts "| #{album.artist} | #{album.name} | #{album.song_play_count} |"
end
file.puts
file.puts '### Cherry-Picked'
file.puts
file.puts '| Artist | Album | Album Plays |'
file.puts '| ------ | ----- | ----------- |'
loyalty[:cherry_picked].each do |album, _cv|
  file.puts "| #{album.artist} | #{album.name} | #{album.song_play_count} |"
end
