#!/usr/bin/env ruby

require './utilities/apple_music_library_parser'

parser = AppleMusicLibraryParser.new('Library.xml')

file = File.open('blog/listening/index.md', 'w')
file.puts '---'
file.puts 'layout: Page'
file.puts 'title: Music Listening'
file.puts 'toc: true'
file.puts 'emoji: 🎶'
file.puts 'searchable: true'
file.puts 'categories:'
file.puts '- blog'
file.puts '- listening'
file.puts 'tags:'
file.puts '- music'
file.puts '- index'
file.puts 'redirect_from:'
file.puts '- /music'
file.puts '---'
file.puts 'I generate this page from my Apple Music library using [a script I wrote](/blog/pulling-fun-insights-out-of-my-apple-music-library). Feel free to use it, too!'
file.puts
file.puts "Last updated: #{DateTime.now.strftime('%Y-%m-%d')}"
file.puts
file.puts '## Top Played Tracks'
file.puts 'This is a list of the top played tracks in my library.'
file.puts
file.puts '| Artist | Album | Track | Play Count | Listening Time |'
file.puts '| ------ | ----- | ----- | ---------- | -------------- |'
parser.top_played_tracks.each do |track|
  time = (track.play_count * track.total_time) / 1000
  time_format = "#{time / 3600}h #{(time % 3600) / 60}m #{time % 60}s"
  file.puts "| #{track.artist} | #{track.album} | #{track.name} | #{track.play_count} | #{time_format} |"
end
file.puts
file.puts '## Top Played Albums'
file.puts 'This is a list of the top played albums in my library (by ratio of song plays to songs in the album).'
file.puts
file.puts '| Artist | Album | Song Play Ratio | Play Count'
file.puts '| ------ | ----- | --------------- | --------- |'
parser.top_played_albums.each do |album|
  file.puts "| #{album.artist} | #{album.name} | #{album.song_play_ratio.round} | #{album.song_play_count} |"
end
file.puts
file.puts '## Top Played Artists'
file.puts 'This is a list of the top played artists in my library (by song plays).'
file.puts
file.puts '| Artist | Song Play Count | Song Play Ratio |'
file.puts '| ------ | -------------- | --------------- |'
parser.top_played_artists.each do |artist|
  file.puts "| #{artist.name} | #{artist.song_play_count} | #{artist.song_play_ratio.round} |"
end
file.puts
file.puts '## Top Genres'
file.puts 'This is a list of the top genres my library (by track count).'
file.puts
file.puts '| Genre | Track Count | Song Play Count | Total Time |'
file.puts '| ------ | ---------- | -------------- | --------------- |'
parser.top_genres.each do |genre|
  time = genre.total_time / 1000
  time_format = "#{time / 3600}h #{(time % 3600) / 60}m #{time % 60}s"
  file.puts "| #{genre.name} | #{genre.track_count} | #{genre.play_count} | #{time_format} |"
end
file.puts
file.puts '## Recently Played Albums'
file.puts 'This is a list of the albums I\'ve played recently.'
file.puts
file.puts '| Artist | Album | Date Added |'
file.puts '| ------ | ----- | --------- |'
parser.recently_played_albums.each do |album|
  file.puts "| #{album.artist} | #{album.name} | #{album.date_added&.strftime('%Y-%m-%d') } |"
end
file.puts
file.puts '## Recently Loved Albums'
file.puts 'This is a list of the albums I\'ve loved recently.'
file.puts
file.puts '| Artist | Album | Date Added |'
file.puts '| ------ | ----- | --------- |'
parser.recently_loved_albums.each do |album|
  file.puts "| #{album.artist} | #{album.name} | #{album.date_added&.strftime('%Y-%m-%d')} |"
end
file.puts
file.puts <<-LIQUID
## Reviews

These are albums that moved me enough to write about.

{% assign postsByMonth = 
site.categories['listening'] | group_by_exp:"post", "post.date | date: '%Y'" %}
{% for day in postsByMonth %}
  <table>
      <thead>
        <tr>
            <td colspan="3">
                <span id="{{ day.name }}">{{ day.name }}</span>
            </td>
        </tr>
      </thead>
  {% for post in day.items %}
  {%- include PostTableRow.html post=post -%}
  {% endfor %}
  </table>
{% endfor %}
LIQUID
