name: Blog Post
description: This template can be used to draft a blog post
labels:
  - post
assignees:
  - joshbeckman
body:
  - type: input
    id: title
    attributes:
      label: Title
    validations:
      required: true
  - type: input
    id: tags
    attributes:
      label: Tags
    validations:
      required: true
  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - "blog"
        - "blog/watching"
        - "blog/reading"
        - "blog/attending"
        - "blog/traveling"
        - "blog/listening"
        - "blog/working"
    validations:
      required: true
  - type: input
    id: date
    attributes:
      label: Date
    validations:
      required: true
  - type: input
    id: imdb_id
    attributes:
      label: IMDB ID
    validations:
      required: false
  - type: dropdown
    id: rating
    attributes:
      label: Rating
      options:
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
    validations:
      required: false
  - type: textarea
    id: content
    attributes:
      label: Content
    validations:
      required: true
